feat: Add actual content

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,19 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-mkdir public
+set -euxo pipefail
 
-echo "You need to wait." > public/index.html
+ZOLA_VERSION=${ZOLA_VERSION:-0.17.2}
+
+rm -rf public/
+
+if [ -x "$(which zola)" ] ; then
+    echo "Zola found, running..."
+    export ZOLA=zola
+else
+    echo "Zola not found, downloading..."
+    wget https://github.com/getzola/zola/releases/download/v$ZOLA_VERSION/zola-v$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz -O zola.tgz
+    tar zxvf zola.tgz
+    export ZOLA=./zola
+fi
+
+$ZOLA build
